"""add has_image flag to post model

Revision ID: 4b5eb594c3e9
Revises: 9c5379ddea77
Create Date: 2019-03-04 18:51:47.979469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b5eb594c3e9'
down_revision = '9c5379ddea77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('has_image', sa.Boolean(), default=False, nullable=False))
    op.alter_column('post', 'has_image',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'has_image')
    # ### end Alembic commands ###
