"""create Post model

Revision ID: 5796a5eb7b81
Revises: fef0b6e1d1a0
Create Date: 2019-01-23 16:00:53.299784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5796a5eb7b81'
down_revision = 'fef0b6e1d1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('writer_id', sa.Integer(), nullable=False),
                    sa.Column('board_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=240), nullable=False),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('is_published', sa.Boolean(), nullable=False, default=True),
                    sa.Column('like_count', sa.Integer(), nullable=False),
                    sa.Column('view_count', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
                    sa.ForeignKeyConstraint(['writer_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('post', 'is_published',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
