"""delete post imagemodel

Revision ID: 63ef99594ca5
Revises: 70b56c2e9428
Create Date: 2019-03-11 16:22:52.003006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63ef99594ca5'
down_revision = '70b56c2e9428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_image',
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('image_url', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('caption', mysql.VARCHAR(collation='utf8mb4_general_ci', length=120), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_image_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
