"""add ondelete set null on foreignkey of user, comment, post

Revision ID: 70b56c2e9428
Revises: c82371f555c8
Create Date: 2019-03-05 11:16:52.192124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70b56c2e9428'
down_revision = 'c82371f555c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['comment_parent_id'], ['id'], onupdate='SET NULL')
    op.alter_column('post', 'writer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'post', 'board', ['board_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'post', 'user', ['writer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'writer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'comment', ['comment_parent_id'], ['id'])
    # ### end Alembic commands ###
