"""Add path column to comment model

Revision ID: adb8fa24130c
Revises: 3b6e2dd5d372
Create Date: 2019-02-08 20:54:04.861668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adb8fa24130c'
down_revision = '3b6e2dd5d372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'path')
    # ### end Alembic commands ###
